<a href="https://colab.research.google.com/github/NitoBoritto/El_Farghaly_Bros./blob/main/notebooks/expirement.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [194]:
import kagglehub
import pandas as pd
import numpy as np

In [195]:
path = kagglehub.dataset_download("vivekvivek13/bank-customers-prediction")
df = pd.read_csv(f"{path}/bank.csv", delimiter=';')

Using Colab cache for faster access to the 'bank-customers-prediction' dataset.

In [196]:
df

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

## Data_Type Function

In [197]:
    # Shows the data type of each column (int, float, object...)

def inspect_data_types(df):
  print("Data Type Inspection")

  return df.dtypes

default : object -> Bool

housing : object -> Bool

loan    : object -> Bool

month   : object -> int OR string

day_of_week : object -> int OR string

## UnKnown Report Function

In [198]:
  # Counts how many 'unknown' values are in each column
def get_unknown_report(df):
    unknown_counts = (df == 'unknown').sum()
    unknown_pct = (unknown_counts / len(df)) * 100

    summary = pd.DataFrame({
        'Unknown Count': unknown_counts,
        'Percentage (%)': unknown_pct.round(2)
    })
    # Filter and sort to show only columns with issues
    return summary[summary['Unknown Count'] > 0].sort_values(by='Unknown Count', ascending=False)

get_unknown_report(df)

           Unknown Count  Percentage (%)
default             8597           20.87
education           1731            4.20
housing              990            2.40
loan                 990            2.40
job                  330            0.80
marital               80            0.19

## Unique Values Report

---

In [199]:

def show_unique_values(df):
    unique_data = []
    for col in df.columns:
        uniques = df[col].unique()
        unique_data.append({
            'Column Name': col,
            'Unique Count': len(uniques),
            'Sample Values': list(uniques[:15])
        })

    report_df = pd.DataFrame(unique_data)

    print(f"{'='*20} Unique Values Report {'='*20}")
    return report_df

show_unique_values(df)

==================== Unique Values Report ====================

,Column Name,Unique Count,Sample Values
0,age,78,"[56, 57, 37, 40, 45, 59, 41, 24, 25, 29, 35, 5..."
1,job,12,"[housemaid, services, admin., blue-collar, tec..."
2,marital,4,"[married, single, divorced, unknown]"
3,education,8,"[basic.4y, high.school, basic.6y, basic.9y, pr..."
4,default,3,"[no, unknown, yes]"
5,housing,3,"[no, yes, unknown]"
6,loan,3,"[no, yes, unknown]"
7,contact,2,"[telephone, cellular]"
8,month,10,"[may, jun, jul, aug, oct, nov, dec, mar, apr, ..."
9,day_of_week,5,"[mon, tue, wed, thu, fri]"
10,duration,1544,"[261, 149, 226, 151, 307, 198, 139, 217, 380, ..."
11,campaign,42,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 19..."
12,pdays,27,"[999, 6, 4, 3, 5, 1, 0, 10, 7, 8, 9, 11, 2, 12..."
13,previous,8,"[0, 1, 2, 3, 4, 5, 6, 7]"
14,poutcome,3,"[nonexistent, failure, success]"
15,emp.var.rate,10,"[1.1, 1.4, -0.1, -0.2, -1.8, -2.9, -3.4, -3.0,..."
16,cons.price.idx,26,"[93.994, 94.465, 93.918, 93.444, 93.798, 93.2,..."
17,cons.conf.idx,26,"[-36.4, -41.8, -42.7, -36.1, -40.4, -42.0, -45..."
18,euribor3m,316,"[4.857, 4.856, 4.855, 4.859, 4.86, 4.858, 4.86..."
19,nr.employed,11,"[5191.0, 5228.1, 5195.8, 5176.3, 5099.1, 5076...."
20,y,2,"[no, yes]"

## Job & Marital & Education

In [200]:
df['job'].unique()

array(['housemaid', 'services', 'admin.', 'blue-collar', 'technician',
       'retired', 'management', 'unemployed', 'self-employed', 'unknown',
       'entrepreneur', 'student'], dtype=object)

In [201]:
df['education'].unique()

array(['basic.4y', 'high.school', 'basic.6y', 'basic.9y',
       'professional.course', 'unknown', 'university.degree',
       'illiterate'], dtype=object)

In [202]:
df['marital'].unique()

array(['married', 'single', 'divorced', 'unknown'], dtype=object)

In [203]:
# Dictionary containing concise English definitions for each job
def display_job_meanings(df):
    job_definitions = {
        'housemaid': 'Responsible for domestic tasks like cleaning and cooking.',
        'services': 'Jobs in the service sector (e.g., retail, waiters, security).',
        'admin.': 'Office administrators and clerical staff.',
        'blue-collar': 'Manual workers in industries like construction or manufacturing.',
        'technician': 'Specialized technical staff (e.g., IT, engineering support).',
        'retired': 'People who have stopped working permanently due to age.',
        'management': 'Executives and department managers with decision-making roles.',
        'unemployed': 'Individuals who are currently not working.',
        'self-employed': 'Individuals working for themselves (freelancers/contractors).',
        'unknown': 'Missing information regarding the client\'s occupation.',
        'entrepreneur': 'Self-employed individuals running their own business ventures.',
        'student': 'People currently enrolled in schools or universities.'
    }

    # Identifying unique values present in the 'job' column
    unique_jobs = df['job'].unique()

    # Printing a structured header
    print(f"\n{'='*80}")
    print(f"{'JOB CATEGORY':<18} | {'ROLE DESCRIPTION'}")
    print(f"{'='*80}")

    # Iterating and printing each job with its meaning
    for job in sorted(unique_jobs):
        meaning = job_definitions.get(job, "Definition not found.")
        print(f"{job.capitalize():<18} | {meaning}")
        print(f"{'-'*80}")

display_job_meanings(df)

================================================================================
JOB CATEGORY       | ROLE DESCRIPTION
================================================================================
Admin.             | Office administrators and clerical staff.
--------------------------------------------------------------------------------
Blue-collar        | Manual workers in industries like construction or manufacturing.
--------------------------------------------------------------------------------
Entrepreneur       | Self-employed individuals running their own business ventures.
--------------------------------------------------------------------------------
Housemaid          | Responsible for domestic tasks like cleaning and cooking.
--------------------------------------------------------------------------------
Management         | Executives and department managers with decision-making roles.
--------------------------------------------------------------------------------
Retired            | People who have stopped working permanently due to age.
--------------------------------------------------------------------------------
Self-employed      | Individuals working for themselves (freelancers/contractors).
--------------------------------------------------------------------------------
Services           | Jobs in the service sector (e.g., retail, waiters, security).
--------------------------------------------------------------------------------
Student            | People currently enrolled in schools or universities.
--------------------------------------------------------------------------------
Technician         | Specialized technical staff (e.g., IT, engineering support).
--------------------------------------------------------------------------------
Unemployed         | Individuals who are currently not working.
--------------------------------------------------------------------------------
Unknown            | Missing information regarding the client's occupation.
--------------------------------------------------------------------------------

In [204]:
def standardize_text_columns(df):

    # 1. Clean 'job' column: Replace '-' and '.' with spaces
    if 'job' in df.columns:
        df['job'] = df['job'].str.replace('-', ' ', regex=False).str.replace('.', ' ', regex=False).str.strip()

    # 2. Clean 'marital' column: Rename 'divorced' to include widowed reference
    if 'marital' in df.columns:
        df['marital'] = df['marital'].replace('divorced', 'divorced & widowed')

    # 3. Clean 'education' column: Map values to the requested school levels
    education_mapping = {
        'basic.4y': 'primary school',
        'basic.6y': 'middle school',
        'basic.9y': 'secondary school',
        'high.school': 'high school',
        'professional.course': 'professional course',
        'university.degree': 'university degree',
        'illiterate': 'illiterate',
        'unknown': 'unknown'
    }

    if 'education' in df.columns:
        df['education'] = df['education'].replace(education_mapping)

    print("--- Cleaning of Job, Marital, and Education columns is complete. ---")
    return df

standardize_text_columns(df)

--- Cleaning of Job, Marital, and Education columns is complete. ---

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,primary school,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin,married,middle school,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional course,no,yes,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue collar,married,professional course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university degree,no,yes,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional course,no,yes,no,cellular,nov,fri,...,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

## Month & Day of Weak  Function
---

In [205]:
df['month'].unique()

array(['may', 'jun', 'jul', 'aug', 'oct', 'nov', 'dec', 'mar', 'apr',
       'sep'], dtype=object)

In [206]:
df['day_of_week'].unique()

array(['mon', 'tue', 'wed', 'thu', 'fri'], dtype=object)

In [207]:
def encode_temporal_columns(df):
    # Convert month names to numbers (Jan=1 → Dec=12)
    month_map = {
        'jan': 1, 'feb': 2, 'mar': 3, 'apr': 4, 'may': 5, 'jun': 6,
        'jul': 7, 'aug': 8, 'sep': 9, 'oct': 10, 'nov': 11, 'dec': 12
    }

    # Convert days to numbers (Mon=1 → Sun=7)
    day_map = {
        'mon': 1, 'tue': 2, 'wed': 3, 'thu': 4,
        'fri': 5, 'sat': 6, 'sun': 7
    }

    # Apply mapping on 'month' column
    if 'month' in df.columns:
        df['month'] = df['month'].str.lower().map(month_map)

    # Apply mapping on 'day_of_week' column
    if 'day_of_week' in df.columns:
        df['day_of_week'] = df['day_of_week'].str.lower().map(day_map)

    print("--- Encoding for 'month' and 'day_of_week' is complete ---")
    return df

# Apply the function
df = encode_temporal_columns(df)
df

--- Encoding for 'month' and 'day_of_week' is complete ---

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,primary school,no,no,no,telephone,5,1,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high school,unknown,no,no,telephone,5,1,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high school,no,yes,no,telephone,5,1,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin,married,middle school,no,no,no,telephone,5,1,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high school,no,no,yes,telephone,5,1,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional course,no,yes,no,cellular,11,5,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue collar,married,professional course,no,no,no,cellular,11,5,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university degree,no,yes,no,cellular,11,5,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional course,no,no,no,cellular,11,5,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional course,no,yes,no,cellular,11,5,...,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

In [208]:
df

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,primary school,no,no,no,telephone,5,1,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high school,unknown,no,no,telephone,5,1,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high school,no,yes,no,telephone,5,1,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin,married,middle school,no,no,no,telephone,5,1,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high school,no,no,yes,telephone,5,1,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional course,no,yes,no,cellular,11,5,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue collar,married,professional course,no,no,no,cellular,11,5,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university degree,no,yes,no,cellular,11,5,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional course,no,no,no,cellular,11,5,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional course,no,yes,no,cellular,11,5,...,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

Warning: Total number of columns (22) exceeds max_columns (20) limiting to first (20) columns.
Warning: total number of rows (41188) exceeds max_rows (20000). Limiting to first (20000) rows.

## Pdays Column
---

In [210]:
np.sort(df['pdays'].unique())

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  25,  26,  27,
       999])

In [211]:
def transform_pdays(df):
    # create new column
    df['pdays_group'] = df['pdays']

    df.loc[df['pdays'] == 999, 'pdays_group'] = 'not contacted'

    mask = df['pdays'] != 999

    df.loc[mask, 'pdays_group'] = pd.cut(
        df.loc[mask, 'pdays'],
        bins=[-1, 3, 7, 14, 30],
        labels=['last 3 days','last week','last 2 weeks','last month']
    )
    return df

transform_pdays(df)

/tmp/ipykernel_497/4266335765.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'not contacted' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df['pdays'] == 999, 'pdays_group'] = 'not contacted'

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,pdays_group
0,56,housemaid,married,primary school,no,no,no,telephone,5,1,...,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,not contacted
1,57,services,married,high school,unknown,no,no,telephone,5,1,...,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,not contacted
2,37,services,married,high school,no,yes,no,telephone,5,1,...,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,not contacted
3,40,admin,married,middle school,no,no,no,telephone,5,1,...,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,not contacted
4,56,services,married,high school,no,no,yes,telephone,5,1,...,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,not contacted
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional course,no,yes,no,cellular,11,5,...,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes,not contacted
41184,46,blue collar,married,professional course,no,no,no,cellular,11,5,...,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no,not contacted
41185,56,retired,married,university degree,no,yes,no,cellular,11,5,...,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no,not contacted
41186,44,technician,married,professional course,no,no,no,cellular,11,5,...,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes,not contacted
41187,74,retired,married,professional course,no,yes,no,cellular,11,5,...,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no,not contacted

In [212]:
df['pdays_group'].unique()

array(['not contacted', 'last week', 'last 3 days', 'last 2 weeks',
       'last month'], dtype=object)

In [213]:
def get_pdays_summary(df):

    # Create a temporary series to hold labels
    temp_series = df['pdays'].astype(object)

    # 1. Identify and label the contacted group
    mask = df['pdays'] != 999
    temp_series.loc[mask] = pd.cut(
        df.loc[mask, 'pdays'],
        bins=[-1, 3, 7, 14, 30],
        labels=['last 3 days', 'last week', 'last 2 weeks', 'last month']
    )

    # 2. Label the 'not contacted' group
    temp_series.loc[df['pdays'] == 999] = 'not contacted'

    # 3. Create the summary table
    summary = temp_series.value_counts().reset_index()
    summary.columns = ['Bin Label', 'Count']
    summary['Percentage (%)'] = (summary['Count'] / len(df) * 100).round(2)

    return summary

get_pdays_summary(df)

       Bin Label  Count  Percentage (%)
0  not contacted  39673           96.32
1      last week    636            1.54
2    last 3 days    541            1.31
3   last 2 weeks    276            0.67
4     last month     62            0.15